apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: prolog-vol
spec:
  source:
    upload: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi