apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: prolog-iso
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: prolog-iso
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - bootOrder: 1
              cdrom:
                bus: sata
              name: cdromiso
            - disk:
                bus: virtio
              name: harddrive
            - cdrom:
                bus: sata
              name: virtiocontainerdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      volumes:
        - name: cdromiso
          persistentVolumeClaim:
            claimName: prolog-iso
        - name: harddrive
          persistentVolumeClaim:
            claimName: prolog-pvc
        - containerDisk:
            image: kubevirt/virtio-container-disk
          name: virtiocontainerdisk